### ISSUE TITLE
Shop issue

### ISSUE THREAD

**Issue by PixelFen** [Nowaha/Shop-by-Conjurate#15]
when i have it set to command, it runs the command but it also says in chat "Your new balance is [current balance].

and when buying an item, it purchases, but it also says in chat saying "A total of 0 failed to purchase"

I've tried deleting and re-adding but it still does it.
Nothing is shown in console so i'm just confused.

**Comment by Huskehhh** [comment]
What version are you using?

**Comment by PixelFen** [comment]
2.5.0

**Comment by Huskehhh** [comment]
#8 #9 #11 

Can you please provide more info (config OR screenshot of item you're selling + item in the store)

Thanks

**Comment by PixelFen** [comment]
Main config:
```
Misc:
  MAIN_PAGE: MAIN
  UPDATE_CHECK: true
  COMMAND_PLACEHOLD: false
Purchase:
  PURCHASE_GUI: ''
  COST_PREFIX: '&aCost&7: &2'
  SHOP_PURCHASE:
  - '&aYou have purchased &b%quantity% &r%item% &afor &2%cost%'
  - '&cA total of &4%failed% &cfailed to purchase.'
  - '&eYour new balance is &2%balance%'
Sell:
  SELL_GUI: ''
  SELL_PREFIX: '&bSell&7: &3'
  SELL_COMPLETE: '&aYou earned &2%worth%'
  SHOP_SELL:
  - '&aYou have sold &b%quantity% &r%item% &afor &2%cost%'
  - '&eYour new balance is &2%balance%'
Trade:
  TRADE_GUI: ''
Messages:
  BLACKLIST_ERROR: '&cYou can''t use the shop in this world'
  PERMISSION_ERROR: '&cYou don''t have permission to use this command'
  COST_CANNOT_AFFORD: '&cYou can''t afford this item'
  TRADE_NEED_SPACE: '&cYou need space in your inventory to complete this trade'
Auto:
  AUTOSAVE: true
  AUTOBACKUP: true
  AUTOSAVE_DELAY: 20
Sign:
  SIGN_TAG: '[shop]'
  SIGN_ENABLED: true
```
Shop's config:
(MAIN.yml)
```
data:
  properties:
    type: 0
    size: 0
    gui: false
  inventory:
    slots:
    - 19
    items:
    - ? v: 1976
        type: DIORITE
      : null
    slotdata:
      '0':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '1':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '2':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '3':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '4':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '5':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '6':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '7':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '8':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '9':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '10':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '11':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '12':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '13':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '14':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '15':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '16':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '17':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '18':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '19':
        page: MAIN
        cost: 5.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: Buy
        guifunction: None
        command:
        - say test
      '20':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '21':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '22':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '23':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '24':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '25':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '26':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '27':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '28':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '29':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '30':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '31':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '32':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '33':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '34':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '35':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '36':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '37':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '38':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '39':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '40':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '41':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '42':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '43':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '44':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '45':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '46':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '47':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '48':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '49':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '50':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '51':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '52':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
      '53':
        page: MAIN
        cost: 0.0
        sell: 0.0
        cooldown: 0
        visibility: Visible
        function: None
        guifunction: None
```
